name:                moon
version:             0.1.0.0
github:              "jacopovalanzano/moon"
license:             MIT
author:              "Jacopo Valanzano"
maintainer:          "jacopov@gmail.com"
copyright:           "2025 Jacopo Valanzano"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            A web framework for Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jacopovalanzano/moon#readme>

dependencies:
- base >= 4.7 && < 5
- filepath >= 1.4
- directory >= 1.3
- cereal
- scotty
- wai
- text
- containers
- stm
- cryptonite
- bytestring
- network
- mysql-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  myproject-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moon

tests:
  myproject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moon
